ALTER AVAILABILITY GROUP [AGName]
MODIFY REPLICA ON 'Replica_Name' WITH (SEEDING_MODE = MANUAL);
GO

ALTER AVAILABILITY GROUP [AGName]
MODIFY REPLICA ON 'Replica_Name' WITH (SEEDING_MODE = AUTOMATIC);
GO
