-- BACKUP SERVICE MASTER KEY
BACKUP SERVICE MASTER KEY TO FILE = 'path_to_file'   
ENCRYPTION BY PASSWORD = 'password'  

-- RESTORE SERVICE MASTER KEY
RESTORE SERVICE MASTER KEY   
FROM FILE = 'c:\temp_backups\keys\service_master_key'   
DECRYPTION BY PASSWORD = '3dH85Hhk003GHk2597gheij4';  
GO  